package com.example.accessingdatamysql;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller // This means that this class is a Controller 这意味着这个类是一个控制器
@RequestMapping(path = "/demo") // This means URL's start with /demo (after Application path) 这意味着URL以/demo开头(在应用程序路径之后)
public class MainController {
    @Autowired // This means to get the bean called userRepository 这意味着获取名为userRepository的bean
    // Which is auto-generated by Spring, we will use it to handle the data 哪些是Spring自动生成的，我们将使用它来处理数据
    private UserRepository userRepository;

    @PostMapping(path = "/add") // Map ONLY POST Requests 仅映射Post请求
    public @ResponseBody String addNewUser(@RequestParam String name, @RequestParam String email) {
        // @ResponseBody means the returned String is the response, not a view name 表示返回的字符串是响应，而不是视图名称
        // @RequestParam means it is a parameter from the GET or POST request 表示它是来自GET或POST请求的参数

        User n = new User();
        n.setName(name);
        n.setEmail(email);
        userRepository.save(n);
        return "Saved";
    }

    @GetMapping(path = "/all")
    public @ResponseBody Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users 这将返回带有用户的JSON或XML
        return userRepository.findAll();
    }

}
